server:
  address: localhost
  port: 8810
banner:
    location: auxiliares/banner.txt
spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/knd?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:oracle:thin:@localhost:1521:xe
    #username: knd
    #password: 1234
    #driver-class-name: oracle.jdbc.OracleDriver
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
                #create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        #dialect: org.hibernate.dialect.Oracle11gDialect
        
  thymeleaf:
    cache: false
        
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: otggc21@gmail.com
    password: Gato2018*
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: true