spring:
  banner:
    location: auxiliares/banner.txt
  datasource:
    url: jdbc:mysql://localhost:3306/knd?useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:oracle:thin:@localhost:1521:xe
    #username: knd
    #password: 1234
    #driver-class-name: oracle.jdbc.OracleDriver
    #com.mysql.jdbc.Driver
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
                #create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      #naming:
       # implicit-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        #dialect: org.hibernate.dialect.Oracle11gDialect